[package]
name = "gpg-alias"
version = "0.1.0"
authors = ["Kyle Clemens <git@kyleclemens.com>"]
edition = "2018"

[dependencies]
ansi_term = "0.11"
clap = "2"
dirs = "1"
fern = "0.5"
gpgme = "0.8"
log = "0.4"
serde = "1"
serde_derive = "1"
toml = "0.4"
